package com.fredprojects.core.database.entities

import androidx.room.*

/**
 * User Entity is used to store user data in the database.
 * @param login is the username of the user.
 * @param password is the password of the user.
 * @param email is the email of the user.
 * @param gender is the gender of the user.
 * @param dateOfBirth is the date of birth of the user. It is used to calculate the age of the user.
 * @param enterDate is the date when the user registered.
 * @param id is unique identifier of the user. It is the primary key of the table and is generated by the database.
 */
@Entity(tableName = "users")
data class UserEntity(
    val login: String,
    val password: String,
    val email: String,
    val gender: Boolean,
    @ColumnInfo(name = "date_of_birth")
    val dateOfBirth: String,
    val enterDate: String,
    @PrimaryKey(autoGenerate = true)
    val id: Int? = null
)